### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by planath** [dev-kitchen/rhino#10]
Einträge sollte man in Englisch und Deutsch speichern können.
Entsprechend auch einen API Parameter gestalten.

**Comment by luxflux** [comment]
Hm, wollen wir hier die API ein wenig umstrukturieren? @planath, @SamuelKupferschmid, @cnworks, was haltet ihr von so einer Struktur `GET /:lang/media/:uuid.json` (z.B. `GET /en/media/1231-123.json`)?

**Comment by planath** [comment]
Macht für mich Sinn :+1: Wenns auch ok für @SamuelKupferschmid ist, hast du das go.

**Comment by luxflux** [comment]
@SamuelKupferschmid und @cnworks wär cool, wenn ihr hier auch noch was sagen könnt.

**Comment by SamuelKupferschmid** [comment]
Für mich auch!
Wird für `/book` und `/chapter` das selbe gelten?

**Comment by luxflux** [comment]
Yep, das ist der Plan.
