### ISSUE TITLE
Titel und Beschreibung werden bei mehreren Einträgen zugleich gesetzt

### ISSUE THREAD

**Issue by planath** [dev-kitchen/rhino#15]
Habe nur das unterste Element editiert. Nach dem Speichern, hat sich jedoch Titel und Beschreibung von Zwei Einträgen verändert.

<img width="907" alt="bildschirmfoto 2016-04-30 um 14 53 37" src="https://cloud.githubusercontent.com/assets/6680829/14935932/9ee245a0-0ee3-11e6-9099-cd650ee2bd0a.png">

**Comment by luxflux** [comment]
Hm... Habe auch versucht das nachzustellen und hat nicht geklappt... @planath, geschieht das immer noch?
