### ISSUE TITLE
Email von Newsletterinteressenten speichern > POST an API

### ISSUE THREAD

**Issue by planath** [dev-kitchen/rhino#5]
Folgendes müsste gespeichert werden:
- [x] Name
- [x] Vorname
- [x] E-Mail-Adresse
- [x] eventuell ob er Android oder iOS user ist
  ...

**Comment by planath** [comment]
Ich schlage Simon Egli vor, dass wir die E-Mail-Adressen bei uns im Backend sichern und ihnen dann eine einfache Export-Funktion anbieten. Bis zu seiner Antwort ist dieser Task on hold.

**Comment by planath** [comment]
Das speichern der Mail-Adressen in unserem Backend mit Export-Funktion von Simi E. abgesegnet.
Findest du das gut so?

**Comment by luxflux** [comment]
Ja, können wir machen.

**Comment by planath** [comment]
Ja dann machen wir das so.

**Comment by luxflux** [comment]
Haha, da habe ich meine eigentliche Antwort/Frage vergessen:

Was meinst Du zu einem solchen API Endpunkt?

```
POST /newsletter_subscriptions
{
  "firstname": "Hans",
  "lastname": "Muster",
  "email": "hans@muster.example",
  "source": "ios"
}
```

Als `source` könnte man dann nur `ios` und `android` verwenden, liesse sich später noch auf anderes erweitern.

**Comment by planath** [comment]
Super perfekt! :smiley:

**Comment by luxflux** [comment]
So, Endpunkt implementiert. Siehe [Dokumentation im README](https://github.com/dev-kitchen/rhino#post-localenewsletter_subscriptions).
