### ISSUE TITLE
HTML Seite wenn QR-Code nicht mit unserer App geöffnet wird

### ISSUE THREAD

**Issue by planath** [dev-kitchen/rhino#7]
Das funktioniert ja bereits :smile:, aber noch anzupassen ist:
- [_] Edit und Back Links entfernen
- [_] Einbinden Link zu iOS und Android App
- [_] Design der DetailView von Stefan anpassen

**Comment by luxflux** [comment]
Hier war mal eine Unterseite auf www.icf.ch (oder so) ein Thema, was ist da der Stand, weisst Du das?

**Comment by planath** [comment]
Das muss ich vergessen haben. Kannst du Simon E. diesbezüglich fragen? Ansonsten einfach über unsere Domain laufen lassen, oder?

**Comment by luxflux** [comment]
Habe gerade mal nachgefragt... Stay tuned.

**Comment by luxflux** [comment]
Die Antwort ist angekommen.

> wir möchten die Website unter icf.church hosten. Wir übernehmen somit die Implementation dieser Seite.
