### ISSUE TITLE
Last changed time stamp

### ISSUE THREAD

**Issue by planath** [dev-kitchen/rhino#8]
Time stamps für Änderungen an Buch / Chapter / Media festhalten.
Somit ermöglichen, nach aktualisiertem Inhalt zu fragen.

**Comment by planath** [comment]
@SamuelKupferschmid hat entsprechend vorgeschlagen einen API point einzurichten, welcher neue Medieninhalte zurückgibt, die jünger als mitgegebenes Datum sind.

**Comment by luxflux** [comment]
Könntet Ihr noch ein wenig genauer definieren was ihr von dem API Endpunkt erwartet? Was für einen Request mit welchen Parametern werdet ihr senden und was erwartet ihr als Antwort?

**Comment by planath** [comment]
Also ein Timestamp für Buch, Chapter und Media wäre praktisch. Zu der API Erweiterung wegen Updates frage ich gleich bei @SamuelKupferschmid nach.

**Comment by SamuelKupferschmid** [comment]
Aktuell gibt es keinen Endpoint, der alle medias auflistet.
Mein Vorschlag:
`https://rhino.dev.kitchen/books/1/media.json?changedsince=1459335710` gibt ein Array aller Medien zurück, die sich seit dem gegebenen Unix-Timestamp geändert haben. 
`changedsince` als url query müsste ebenfalls für chapters und books implementiert werden.
Ziel ist, dass Änderungen (Schreibfehler, neuere Videos, verwaiste Links) im nachhinein auf dem Client aktualisiert werden. Die Mobile-Clients werden die Änderungen sporadisch im Hintergrund abgleichen.
